-- Run this once in your Supabase project's SQL Editor (Database > SQL Editor > New query)

create table if not exists ucc_saves (
  id bigint generated by default as identity primary key,
  name text not null,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

alter table ucc_saves enable row level security;

-- Open policies: anyone with your anon/publishable key can read/write.
-- Fine for a small internal tool with no user accounts. Tighten later if needed.
create policy "public read" on ucc_saves for select using (true);
create policy "public insert" on ucc_saves for insert with check (true);
create policy "public update" on ucc_saves for update using (true);
create policy "public delete" on ucc_saves for delete using (true);
